package com.jtrent238.foodmod

import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.Property;

public class FoodModConfig
{
  static int itemchocolatecakeID;
  static int itemapplecakeID;
  static int itemcarrotcakeID;
  static int itemmagiccakeID;
  static int blockchocolateID;
  static int itemcaramelcakeID;
  static int itemapplesapling;
  static int itemlemonsapling;
  static int blockstove;
  static int blockmicrowave;
  static int blockfridge;
  static int plantpeanut;
  public static int AppleCakeItemID;
  public static int ChocoCakeItemID;
  public static int CarrotCakeItemID;
  public static int CaramelCakeItemID;
  public static int itemmilkbottleID;
  public static int itembanana;
  public static int itemgrits;
  public static int itembean;
  public static int itempopcorn;
  public static int itemcorn;
  public static int itemlettuce;
  public static int itemtomato;
  public static int itemgreen_tomato;
  public static int itemblackbeans;
  public static int itemlime;
  public static int itemgrape;
  public static int itemcream;
  public static int itembutter;
  public static int itemice;
  public static int itempufferfish_cooked;
  public static int itemclownfish_raw;
  public static int itemcheese;
  public static int itemgrilledcheese;
  public static int itemgrilledcheesesandwhich;
  public static int itemdiamondapple;
  public static int itemcoalapple;
  public static int itemredstoneapple;
  public static int itemgoldapple;
  public static int itememeraldapple;
  public static int itemlapizapple;
  public static int itemironapple;
  public static int itemnetherstarapple;
  public static int itemdragoneggapple;
  public static int itemflesh;
  public static int itemcookedflesh;
  public static int itembacon;
  public static int itemcheesecake;
  public static int itemcarrotcake;
  public static int itemBakersyeast;
  public static int itemBarkbread;
  public static int itemKubdari;
  public static int itemKisra;
  public static int itemSimit;
  public static int itemRicebread;
  public static int itemtoast;
  public static int itemČesnica;
  public static int itemSlicedbread;
  public static int itemchocolatebar;
  public static int itemchocolatemilk;
  public static int itempizza;
  public static int itemicecream;
  public static int itemcorndog;
  public static int itemcorndog_mustard;
  public static int itemcorndog_ketchup;
  public static int itemhotdog;
  public static int itemcottoncandy;
  public static int itemapplepie;
  public static int itemcandyapple;
  public static int itemsugarcookie;
  public static int itemoreo;
  public static int item_mms;
  public static int itemlemonade;
  public static int itemlemon;
  public static int itemmeatball;
  public static int itemmeatballraw;
  public static int itempasta;
  public static int itemchickenwings;
  public static int itemchickenwingsraw;
  public static int itemchicken_nuggets;
  public static int itemchicken_nuggetsraw;
  public static int itempeanut;
  public static int itempeanutseeds;
  public static int itempeanutPlant;
  public static int itembean;
  public static int itemgoatmilk;
  public static int itemfishsticks;
  public static int itemfishsticksraw;
  public static int itempie;
  public static int itemmutton;
  public static int itemmuttonraw;
  public static int itemlamb;
  public static int itemlambraw;
  public static int itemCheesecakeStuffedStrawberries;
  public static int itemstrawberry;
  public static int itemblueberry;
  public static int itemblackberry;
  public static int itemcherry;
  public static int itemsoup;
  public static int itemfrenchfry;
  public static int itemlemonpie;
  public static int itemapplepie;
  public static int itemasparagus;
  public static int itembasil;
  public static int itemcilantro;
  public static int itembroccoli;
  public static int itemorange;
  public static int itemkiwi;
  public static int itemredpepper;
  public static int itemtomato;
  public static int itemavocado;
  public static int itemgreenpepper;
  public static int itemraspberries;
  public static int itempear;
  public static int itempeach;
  public static int itemonions;
  public static int itemgarlic;
  public static int itemginger;
  public static int itemadzukibeans;
  public static int itemblackbeans;
  public static int itemblackeyepeas;
  public static int itemgarbanzobeans;
  public static int itemkidneybeans;
  public static int itemlentils;
  public static int itempintobeans;
  public static int itemwhitebeans;
  public static int itembeetroot;
  public static int itemknife;
  public static int itemfork;
  public static int itemspoon;
  public static int itemplate;
  public static int itembowl;
  public static int itemtowel;
  public static int itemnapkin;
  public static int itemappleseed;
  public static Configuration config;
  
  public static void FC_Configuration(FMLPreInitializationEvent event)
  {
    config = new Configuration(event.getSuggestedConfigurationFile());
    config.load();
    
    itemmilkbottleID = config.getItem("Milk Bottle", 4041).getInt();
    
    itemchocolatecakeID = config.getBlock("Chocolate Cake", 503).getInt();
    itemapplecakeID = config.getBlock("Apple Cake", 504).getInt();
    itemcarrotcakeID = config.getBlock("Carrot Cake", 505).getInt();
    itemmagiccakeID = config.getBlock("Magic Cake", 506).getInt();
    blockchocolateID = config.getBlock("Chocolate Block", 507).getInt();
    itemcaramelcakeID = config.getBlock("Caramel Cake", 509).getInt();
    
    ChocoCakeItemID = config.getItem("ChocoCakeItem", 4016).getInt();
    AppleCakeItemID = config.getItem("AppleCakeItem", 4017).getInt();
    CarrotCakeItemID = config.getItem("CarrotCakeItem", 4018).getInt();
    MagicCakeItemID = config.getItem("MagicCakeItem", 4019).getInt();
    
    config.save();
  }
}
