package com.jtrent238.foodmod;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemFood;
import net.minecraft.potion.Potion;
import com.jtrent238.foodmod.config;

public class ItemLoader {

	//Items
			//Food
		public static Item itemcheese;
		public static Item itemgrilledcheese;
		public static Item itemgrilledcheesesandwhich;
		public static Item itemdiamondapple;
		public static Item itemcoalapple;
		public static Item itemredstoneapple;
		public static Item itemgoldapple;
		public static Item itememeraldapple;
		public static Item itemlapizapple;
		public static Item itemironapple;
		public static Item itemnetherstarapple;
		public static Item itemdragoneggapple;
		public static Item itemflesh;
		public static Item itemcookedflesh;
		public static Item itembacon;
		public static Item itemcheesecake;
		public static Item itemcarrotcake;
		public static Item itemBakersyeast;
		public static Item itemBarkbread;
		public static Item itemKubdari;
		public static Item itemKisra;
		public static Item itemSimit;
		public static Item itemRicebread;
		public static Item itemtoast;
		public static Item itemČesnica;
		public static Item itemSlicedbread;
		public static Item itemchocolatebar;
		public static Item itemchocolatemilk;
		public static Item itempizza;
		public static Item itemicecream;
		public static Item itemcorndog;
		public static Item itemcorndog_mustard;
		public static Item itemcorndog_ketchup;
		public static Item itemhotdog;
		public static Item itemcottoncandy_pink;
		public static Item itemcottoncandy_blue;
		public static Item itemcandyapple;
		public static Item itemsugarcookie;
		public static Item itemoreo;
		public static Item item_mms;
		public static Item itemlemonade;
		public static Item itemlemon;
		public static Item itemmeatball;
		public static Item itemmeatballraw;
		public static Item itempasta;
		public static Item itemchickenwings;
		public static Item itemchickenwingsraw;
		public static Item itemchicken_nuggets;
		public static Item itemchicken_nuggetsraw;
		public static Item itempeanut;
		public static Item itempeanutseeds;
		public static Item itempeanutPlant;
		public static Item itembean;
		public static Item itemgoatmilk;
		public static Item itemfishsticks;
		public static Item itemfishsticksraw;
		public static Item itempie;
		public static Item itemmutton;
		public static Item itemmuttonraw;
		public static Item itemlamb;
		public static Item itemlambraw;
		public static Item itemCheesecakeStuffedStrawberries;
		public static Item itemstrawberry;
		public static Item itemblueberry;
		public static Item itemblackberry;
		public static Item itemcherry;
		public static Item itemsoup;
		public static Item itemfrenchfry;
		public static Item itemlemonpie;
		public static Item itemapplepie;
		public static Item itemasparagus;
		public static Item itembasil;
		public static Item itemcilantro;
		public static Item itembroccoli;
		public static Item itemorange;
		public static Item itemkiwi;
		public static Item itemredpepper;
		public static Item itemtomato;
		public static Item itemavocado;
		public static Item itemgreenpepper;
		public static Item itemraspberries;
		public static Item itempear;
		public static Item itempeach;
		public static Item itemonions;
		public static Item itemgarlic;
		public static Item itemginger;
		public static Item itemadzukibeans;
		public static Item itemblackbeans;
		public static Item itemblackeyepeas;
		public static Item itemgarbanzobeans;
		public static Item itemkidneybeans;
		public static Item itemlentils;
		public static Item itempintobeans;
		public static Item itemwhitebeans;
		public static Item itembeetroot;
		public static Item itemcreamcheese;
		public static Item itemchedderchesse;
		public static Item itemchocolateicecream;
		public static Item itemcream;
		public static Item itemwhipcream;
		public static Item itemcoolwhip;
		public static Item itembanana;
		public static Item itemgrits;
		public static Item itempopcorn;
		public static Item itemcorn;
		public static Item itemlettuce;
		public static Item itemgreen_tomato;
		public static Item itemlime;
		public static Item itemgrape;
		public static Item itembutter;
		public static Item itemice;
		public static Item itempufferfish_cooked;
		public static Item itemclownfish_cooked;
		public static Item itemmilkbottle;
		public static Item itemchocolatecake;
		public static Item itemapplecake;
		public static Item itemmagiccake;
		public static Item itemcaramelcake;
		public static Item itemchickensoup;
		public static Item itemchickenlegraw;
		public static Item itemchickenleg;
		public static Item itemcabbage;
		public static Item itembun;
		public static Item itempickle;
		public static Item itemcucumber;
		public static Item itemsquash;
		public static Item itemsugarcube;
		public static Item itemflour;
		public static Item itemlemonjuice;
		public static Item itemmashedbananas;
		public static Item itemchoppednuts;
		public static Item itemchoppedgrass;
		public static Item itembakingpowder;
		public static Item itemcinnamon;
		public static Item itemgroundginger;
		public static Item itemalmonds;
		public static Item itemgroundalmonds;
		public static Item itemhoney;
		public static Item itemsesameseeds;
		public static Item itemshortening;
		public static Item itembrownsugar;
		public static Item itemmeltedbutter;
		public static Item itembayleaf;
		public static Item itemhamburger;
		public static Item itembeefbroth;
		public static Item itemjalapenopeppers;
		public static Item itemmintleaves;
		public static Item itemcocacolabottle_empty;
		public static Item itembuttercandy;
		public static Item itemhorsemeat;
		public static Item itemhorsemeat_raw;
		public static Item itemluckycandy;
		public static Item itemunstablecandy;
		public static Item itemcandyboat;
		public static Item itemcandycane;
		public static Item itemcandycanestick;
		public static Item itemcandycanereed;
		public static Item itemnyanapple;
		public static Item itemOven;
		public static Item itemcandyarrow;
		public static Item itemcandybow;
		public static Item itemcandybed;
		public static Item itemdrink;
		public static Item itemfriedegg;
		
		//Structure Placers
		public static Item itemcandycanestructure;
		
		//Puddings
		public static Item itemvanillapuding;
		public static Item itemchocolatepuding;
		public static Item itemstrawberrypudding;
		public static Item itembananapudding;
		public static Item itemlemonpudding;
		public static Item itemcookiesncreampudding;
		public static Item itempistachiopudding;
		
			//Drinks
		public static Item itemtea;
		
			//Sauces
		public static Item itemsteaksause;
		public static Item itemmustard;
		public static Item itemketchup;
		public static Item itemmayo;
		public static Item itemhoneymustard;
		public static Item itemranch;
		public static Item itemA1;
		
		
		public static Item itemsalt;
		public static Item itempepper;

		
		
			//Kitchen Utensils
		public static Item itemknife;
		public static Item itemfork;
		public static Item itemspoon;
		public static Item itemplate;
		public static Item itembowl;
		public static Item itemtowel;
		public static Item itemnapkin;

		
		//Potion Apples
		public static Item itemapple_swiftness;
		public static Item itemapple_strength;
		public static Item itemapple_posion;
		public static Item itemapple_fireresistance;
		public static Item itemapple_regeneration;
		public static Item itemapple_waterbreathing;
		public static Item itemapple_jump;
		
			//Seeds
		public static Item itemappleseed;

		public static int randomItemID;

		
		/**
		 * Load Items.
		 */
	public static void LoadItems() {
	    itemdiamondapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itemdiamondapple").setTextureName("foodmod:itemdiamondapple").setCreativeTab(FoodMod.FoodMod);
	    itemcoalapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itemcoalapple").setTextureName("foodmod:itemcoalapple").setCreativeTab(FoodMod.FoodMod);
	    itemgoldapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itemgoldapple").setTextureName("foodmod:itemgoldapple").setCreativeTab(FoodMod.FoodMod);
	    itemredstoneapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itemredstoneapple").setTextureName("foodmod:itemredstoneapple").setCreativeTab(FoodMod.FoodMod);
	    itememeraldapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itememeraldapple").setTextureName("foodmod:itememeraldapple").setCreativeTab(FoodMod.FoodMod);
	    itemlapizapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itemlapizapple").setTextureName("foodmod:itemlapizapple").setCreativeTab(FoodMod.FoodMod);
	    itemironapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itemironapple").setTextureName("foodmod:itemironapple").setCreativeTab(FoodMod.FoodMod);
	    itemnetherstarapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itemnetherstarapple").setTextureName("foodmod:itemnetherstarapple").setCreativeTab(FoodMod.FoodMod);
	    itemdragoneggapple = new ItemFood(5, 0.2F, false).setUnlocalizedName("itemdragoneggapple").setTextureName("foodmod:itemdragoneggapple").setCreativeTab(FoodMod.FoodMod);
	    itemcheese = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcheese").setTextureName("foodmod:itemgrilledcheese").setCreativeTab(FoodMod.FoodMod);
	    itemgrilledcheese = new ItemFood(6, 0.2F, false).setUnlocalizedName("itemgrilledcheese").setTextureName("foodmod:itemgrilledcheese").setCreativeTab(FoodMod.FoodMod);
	    itemflesh = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemflesh").setTextureName("foodmod:itemflesh").setCreativeTab(FoodMod.FoodMod);
	    itemcookedflesh = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemcookedflesh").setTextureName("foodmod:itemcookedflesh").setCreativeTab(FoodMod.FoodMod);
	    itembacon = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembacon").setTextureName("foodmod:itembacon").setCreativeTab(FoodMod.FoodMod);
	    itemcheesecake = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcheesecake").setTextureName("foodmod:itemcheesecake").setCreativeTab(FoodMod.FoodMod);
	    itemcarrotcake = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcarrotcake").setTextureName("foodmod:itemcarrotcake").setCreativeTab(FoodMod.FoodMod);
	    itemBarkbread = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemBarkbread").setTextureName("foodmod:itemBarkbread").setCreativeTab(FoodMod.FoodMod);
	    itemKubdari = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemKubdari").setTextureName("foodmod:itemKubdari").setCreativeTab(FoodMod.FoodMod);
	    itemRicebread = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemRicebread").setTextureName("foodmod:itemRicebread").setCreativeTab(FoodMod.FoodMod);
	    itemtoast = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemtoast").setTextureName("foodmod:itemtoast").setCreativeTab(FoodMod.FoodMod);
	    itemČesnica = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemČesnica").setTextureName("foodmod:itemČesnica").setCreativeTab(FoodMod.FoodMod);
	    itemSlicedbread = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemSlicedbread").setTextureName("foodmod:itemSlicedbread").setCreativeTab(FoodMod.FoodMod);
	    itemchocolatebar = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemchocolatebar").setTextureName("foodmod:itemchocolatebar").setCreativeTab(FoodMod.FoodMod);
	    itemchocolatemilk = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemchocolatemilk").setTextureName("foodmod:itemchocolatemilk").setCreativeTab(FoodMod.FoodMod);
	    itempizza = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempizza").setTextureName("foodmod:itempizza").setCreativeTab(FoodMod.FoodMod);
	    itemicecream = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemicecream").setTextureName("foodmod:itemicecream").setCreativeTab(FoodMod.FoodMod);
	    itemcorndog = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcorndog").setTextureName("foodmod:itemcorndog").setCreativeTab(FoodMod.FoodMod);
	    itemcorndog_ketchup = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcorndog_ketchup").setTextureName("foodmod:itemcorndog_ketchup").setCreativeTab(FoodMod.FoodMod);
	    itemcorndog_mustard = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcorndog_mustard").setTextureName("foodmod:itemcorndog_mustard").setCreativeTab(FoodMod.FoodMod);
	    itemhotdog = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemhotdog").setTextureName("foodmod:itemhotdog").setCreativeTab(FoodMod.FoodMod);
	    itemcottoncandy_pink = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcottoncandy_pink").setTextureName("foodmod:itemcottoncandy_pink").setCreativeTab(FoodMod.FoodMod);
	    itemcottoncandy_blue = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcottoncandy_blue").setTextureName("foodmod:itemcottoncandy_blue").setCreativeTab(FoodMod.FoodMod);
	    itemapplepie = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemapplepie").setTextureName("foodmod:itemapplepie").setCreativeTab(FoodMod.FoodMod);
	    itemcandyapple = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcandyapple").setTextureName("foodmod:itemcandyapple").setCreativeTab(FoodMod.FoodMod);
	    itemsugarcookie = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemsugarcookie").setTextureName("foodmod:itemsugarcookie").setCreativeTab(FoodMod.FoodMod);
	    itemoreo = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemoreo").setTextureName("foodmod:itemoreo").setCreativeTab(FoodMod.FoodMod);
	    item_mms = new ItemFood(3, 0.2F, false).setUnlocalizedName("item_mms").setTextureName("foodmod:item_mms").setCreativeTab(FoodMod.FoodMod);
	    itemlemonade = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemlemonade").setTextureName("foodmod:itemlemonade").setCreativeTab(FoodMod.FoodMod);
	    itemlemon = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemlemon").setTextureName("foodmod:itemlemon").setCreativeTab(FoodMod.FoodMod);
	    itemmeatball = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemmeatball").setTextureName("foodmod:itemmeatball").setCreativeTab(FoodMod.FoodMod);
	    itemmeatballraw = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemmeatballraw").setTextureName("foodmod:itemmeatballraw").setCreativeTab(FoodMod.FoodMod);
	    itempasta = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempasta").setTextureName("foodmod:itempasta").setCreativeTab(FoodMod.FoodMod);
	    itempeanut = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempeanut").setTextureName("foodmod:itempeanut").setCreativeTab(FoodMod.FoodMod);
	    itembean = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembean").setTextureName("foodmod:itembean").setCreativeTab(FoodMod.FoodMod);
	    itemgoatmilk = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgoatmilk").setTextureName("foodmod:itemgoatmilk").setCreativeTab(FoodMod.FoodMod);
	    itemfishsticks = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemfishsticks").setTextureName("foodmod:itemfishsticks").setCreativeTab(FoodMod.FoodMod);
	    itemfishsticksraw = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemfishsticksraw").setTextureName("foodmod:itemfishsticksraw").setCreativeTab(FoodMod.FoodMod);
	    itempie = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempie").setTextureName("foodmod:itempie").setCreativeTab(FoodMod.FoodMod);
	    itemmutton = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemmutton").setTextureName("foodmod:itemmutton").setCreativeTab(FoodMod.FoodMod);
	    itemmuttonraw = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemmuttonraw").setTextureName("foodmod:itemmuttonraw").setCreativeTab(FoodMod.FoodMod);
	    itemlamb = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemlamb").setTextureName("foodmod:itemlamb").setCreativeTab(FoodMod.FoodMod);
	    itemlambraw = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemlambraw").setTextureName("foodmod:itemlambraw").setCreativeTab(FoodMod.FoodMod);
	    itemCheesecakeStuffedStrawberries = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemCheesecakeStuffedStrawberries").setTextureName("foodmod:itemCheesecakeStuffedStrawberries").setCreativeTab(FoodMod.FoodMod);
	    itemstrawberry = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemstrawberry").setTextureName("foodmod:itemstrawberry").setCreativeTab(FoodMod.FoodMod);
	    itemblueberry = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemblueberry").setTextureName("foodmod:itemblueberry").setCreativeTab(FoodMod.FoodMod);
	    itemblackberry = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemblackberry").setTextureName("foodmod:itemblackberry").setCreativeTab(FoodMod.FoodMod);
	    itemcherry = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcherry").setTextureName("foodmod:itemcherry").setCreativeTab(FoodMod.FoodMod);
	    itemsoup = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemsoup").setTextureName("foodmod:itemsoup").setCreativeTab(FoodMod.FoodMod);
	    itemfrenchfry = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemfrenchfry").setTextureName("foodmod:itemfrenchfry").setCreativeTab(FoodMod.FoodMod);
	    itemlemonpie = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemlemonpie").setTextureName("foodmod:itemlemonpie").setCreativeTab(FoodMod.FoodMod);
	    itemasparagus = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemasparagus").setTextureName("foodmod:itemasparagus").setCreativeTab(FoodMod.FoodMod);
	    itembasil = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembasil").setTextureName("foodmod:itembasil").setCreativeTab(FoodMod.FoodMod);
	    itemcilantro = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcilantro").setTextureName("foodmod:itemcilantro").setCreativeTab(FoodMod.FoodMod);
	    itembroccoli = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembroccoli").setTextureName("foodmod:itembroccoli").setCreativeTab(FoodMod.FoodMod);
	    itemorange = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemorange").setTextureName("foodmod:itemorange").setCreativeTab(FoodMod.FoodMod);
	    itemkiwi = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemkiwi").setTextureName("foodmod:itemkiwi").setCreativeTab(FoodMod.FoodMod);
	    itemredpepper = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemredpepper").setTextureName("foodmod:itemredpepper").setCreativeTab(FoodMod.FoodMod);
	    itemtomato = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemtomato").setTextureName("foodmod:itemtomato").setCreativeTab(FoodMod.FoodMod);
	    itemavocado = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemavocado").setTextureName("foodmod:itemavocado").setCreativeTab(FoodMod.FoodMod);
	    itemgreenpepper = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgreenpepper").setTextureName("foodmod:itemgreenpepper").setCreativeTab(FoodMod.FoodMod);
	    itemraspberries = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemraspberries").setTextureName("foodmod:itemraspberries").setCreativeTab(FoodMod.FoodMod);
	    itempear = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempear").setTextureName("foodmod:itempear").setCreativeTab(FoodMod.FoodMod);
	    itempeach = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempeach").setTextureName("foodmod:itempeach").setCreativeTab(FoodMod.FoodMod);
	    itemonions = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemonions").setTextureName("foodmod:itemonions").setCreativeTab(FoodMod.FoodMod);
	    itemgarlic = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgarlic").setTextureName("foodmod:itemgarlic").setCreativeTab(FoodMod.FoodMod);
	    itemginger = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemginger").setTextureName("foodmod:itemginger").setCreativeTab(FoodMod.FoodMod);
	    itemadzukibeans = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemadzukibeans").setTextureName("foodmod:itemadzukibeans").setCreativeTab(FoodMod.FoodMod);
	    itemblackbeans = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemblackbeans").setTextureName("foodmod:itemblackbeans").setCreativeTab(FoodMod.FoodMod);
	    itemblackeyepeas = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemblackeyepeas").setTextureName("foodmod:itemblackeyepeas").setCreativeTab(FoodMod.FoodMod);
	    itemgarbanzobeans = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgarbanzobeans").setTextureName("foodmod:itemgarbanzobeans").setCreativeTab(FoodMod.FoodMod);
	    itemkidneybeans = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemkidneybeans").setTextureName("foodmod:itemkidneybeans").setCreativeTab(FoodMod.FoodMod);
	    itemlentils = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemlentils").setTextureName("foodmod:itemlentils").setCreativeTab(FoodMod.FoodMod);
	    itempintobeans = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempintobeans").setTextureName("foodmod:itempintobeans").setCreativeTab(FoodMod.FoodMod);
	    itemwhitebeans = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemwhitebeans").setTextureName("foodmod:itemwhitebeans").setCreativeTab(FoodMod.FoodMod);
	    itembeetroot = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembeetroot").setTextureName("foodmod:itembeetroot").setCreativeTab(FoodMod.FoodMod);
	    itemmustard = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemmustard").setTextureName("foodmod:itemmustard").setCreativeTab(FoodMod.FoodMod);
	    itemketchup = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemketchup").setTextureName("foodmod:itemketchup").setCreativeTab(FoodMod.FoodMod);
	    itemmayo = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemmayo").setTextureName("foodmod:itemmayo").setCreativeTab(FoodMod.FoodMod);
	    itemhoneymustard = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemhoneymustard").setTextureName("foodmod:itemhoneymustard").setCreativeTab(FoodMod.FoodMod);
	    itemranch = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemranch").setTextureName("foodmod:itemranch").setCreativeTab(FoodMod.FoodMod);
	    itembanana = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembanana").setTextureName("foodmod:itembanana").setCreativeTab(FoodMod.FoodMod);
	    itemgrits = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgrits").setTextureName("foodmod:itemgrits").setCreativeTab(FoodMod.FoodMod);
	    itempopcorn = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempopcorn").setTextureName("foodmod:itempopcorn").setCreativeTab(FoodMod.FoodMod);
	    itemcorn = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcorn").setTextureName("foodmod:itemcorn").setCreativeTab(FoodMod.FoodMod);
	    itemlettuce = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemlettuce").setTextureName("foodmod:itemlettuce").setCreativeTab(FoodMod.FoodMod);
	    itemgreen_tomato = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgreen_tomato").setTextureName("foodmod:itemgreen_tomato").setCreativeTab(FoodMod.FoodMod);
	    itemlime = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemlime").setTextureName("foodmod:itemlime").setCreativeTab(FoodMod.FoodMod);
	    itemgrape = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgrape").setTextureName("foodmod:itemgrape").setCreativeTab(FoodMod.FoodMod);
	    itemcream = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcream").setTextureName("foodmod:itemcream").setCreativeTab(FoodMod.FoodMod);
	    itembutter = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembutter").setTextureName("foodmod:itembutter").setCreativeTab(FoodMod.FoodMod);
	    itemice = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemice").setTextureName("foodmod:itemice").setCreativeTab(FoodMod.FoodMod);
	    itempufferfish_cooked = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempufferfish_cooked").setTextureName("foodmod:itempufferfish_cooked").setCreativeTab(FoodMod.FoodMod);
	    itemclownfish_cooked = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemclownfish_cooked").setTextureName("foodmod:itemclownfish_cooked").setCreativeTab(FoodMod.FoodMod);
	    itemchickensoup = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemchickensoup").setTextureName("foodmod:itemchickensoup").setCreativeTab(FoodMod.FoodMod);
	    itemchickenwings = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemchickenwings").setTextureName("foodmod:itemchickenwing").setCreativeTab(FoodMod.FoodMod);
	    itemchickenwingsraw = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemchickenwingsraw").setTextureName("foodmod:itemchickenwing_raw").setCreativeTab(FoodMod.FoodMod);
	    itemchickenleg = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemchickenleg").setTextureName("foodmod:itemchickenleg").setCreativeTab(FoodMod.FoodMod);
	    itemchickenlegraw = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemchickenlegraw").setTextureName("foodmod:itemchickenleg_raw").setCreativeTab(FoodMod.FoodMod);
	    itemchicken_nuggets = new ItemFood(5, 0.2F, true).setUnlocalizedName("itemchicken_nuggets").setTextureName("foodmod:itemchicken_nuggets").setCreativeTab(FoodMod.FoodMod);
	    itemchicken_nuggetsraw = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemchicken_nuggetsraw").setTextureName("foodmod:itemchicken_nuggetsraw").setCreativeTab(FoodMod.FoodMod);
	    itemcabbage = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcabbage").setTextureName("foodmod:itemcabbage").setCreativeTab(FoodMod.FoodMod);
	    itembun = new ItemFood(3, 0.2F, true).setUnlocalizedName("itembun").setTextureName("foodmod:itembun").setCreativeTab(FoodMod.FoodMod);
	    itempickle = new ItemFood(3, 0.2F, false).setUnlocalizedName("itempickle").setTextureName("foodmod:itempickle").setCreativeTab(FoodMod.FoodMod);
	    itemcucumber = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcucumber").setTextureName("foodmod:itemcucumber").setCreativeTab(FoodMod.FoodMod);
	    itemsquash = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemsquash").setTextureName("foodmod:itemsquash").setCreativeTab(FoodMod.FoodMod);
	    itemlemonjuice = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemlemonjuice").setTextureName("foodmod:itemlemonjuice").setCreativeTab(FoodMod.FoodMod);
	    itemmashedbananas = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemmashedbananas").setTextureName("foodmod:itemmashedbananas").setCreativeTab(FoodMod.FoodMod);
	    itemchoppednuts = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemchoppednuts").setTextureName("foodmod:itemchoppednuts").setCreativeTab(FoodMod.FoodMod);
	    itemchoppedgrass = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemchoppedgrass").setTextureName("foodmod:itemchoppedgrass").setCreativeTab(FoodMod.FoodMod);
	    itembakingpowder = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembakingpowder").setTextureName("foodmod:itembakingpowder").setCreativeTab(FoodMod.FoodMod);
	    itemcinnamon = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemcinnamon").setTextureName("foodmod:itemcinnamon").setCreativeTab(FoodMod.FoodMod);
	    itemgroundginger = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgroundginger").setTextureName("foodmod:itemgroundginger").setCreativeTab(FoodMod.FoodMod);
	    itemalmonds = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemalmonds").setTextureName("foodmod:itemalmonds").setCreativeTab(FoodMod.FoodMod);
	    itemgroundalmonds = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemgroundalmonds").setTextureName("foodmod:itemgroundalmonds").setCreativeTab(FoodMod.FoodMod);
	    itemhoney = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemhoney").setTextureName("foodmod:itemhoney").setCreativeTab(FoodMod.FoodMod);
	    itemsesameseeds = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemsesameseeds").setTextureName("foodmod:itemsesameseeds").setCreativeTab(FoodMod.FoodMod);
	    itemshortening = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemshortening").setTextureName("foodmod:itemshortening").setCreativeTab(FoodMod.FoodMod);
	    itembrownsugar = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembrownsugar").setTextureName("foodmod:itembrownsugar").setCreativeTab(FoodMod.FoodMod);
	    itemmeltedbutter = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemmeltedbutter").setTextureName("foodmod:itemmeltedbutter").setCreativeTab(FoodMod.FoodMod);
	    itembayleaf = new ItemFood(3, 0.2F, false).setUnlocalizedName("itembayleaf").setTextureName("foodmod:itembayleaf").setCreativeTab(FoodMod.FoodMod);
	    itemhamburger = new ItemFood(10, 0.2F, true).setUnlocalizedName("itemhamburger").setTextureName("foodmod:itemhamburger").setCreativeTab(FoodMod.FoodMod);
	    itembeefbroth = new ItemFood(3, 0.2F, true).setUnlocalizedName("itembeefbroth").setTextureName("foodmod:itembeefbroth").setCreativeTab(FoodMod.FoodMod);
	    itemjalapenopeppers = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemjalapenopeppers").setTextureName("foodmod:itemjalapenopeppers").setCreativeTab(FoodMod.FoodMod);
	    itemmintleaves = new ItemFood(3, 0.2F, false).setUnlocalizedName("itemmintleaves").setTextureName("foodmod:itemmintleaves").setCreativeTab(FoodMod.FoodMod);
	    itembuttercandy = new ItemFood(2, 0.2F, false).setUnlocalizedName("itembuttercandy").setTextureName("foodmod:itembuttercandy").setCreativeTab(FoodMod.FoodMod);
	    itemhorsemeat = new ItemFood(8, 0.2F, true).setUnlocalizedName("itemhorsemeat").setTextureName("foodmod:itemhorsemeat").setCreativeTab(FoodMod.FoodMod);
	    itemhorsemeat_raw = new ItemFood(3, 0.2F, true).setUnlocalizedName("itemhorsemeat_raw").setTextureName("foodmod:itemhorsemeat_raw").setCreativeTab(FoodMod.FoodMod);
	    itemluckycandy = new ItemLuckyCandy(6, 0.2F, false).setUnlocalizedName("itemluckycandy").setTextureName("foodmod:itemluckycandy").setCreativeTab(FoodMod.FoodMod);
	    itemunstablecandy = new itemunstablecandy().setUnlocalizedName("itemunstablecandy").setTextureName("foodmod:itemunstablecandy").setCreativeTab(FoodMod.FoodMod);
	    itemsugarcube = new Itemsugarcube().setUnlocalizedName("itemsugarcube").setTextureName("foodmod:itemsugarcube").setCreativeTab(FoodMod.FoodMod);
		itemflour = new Itemflour().setUnlocalizedName("itemflour").setTextureName("foodmod:itemflour").setCreativeTab(FoodMod.FoodMod);
		itemapple_swiftness = new Itemapple_swiftness(4, 0.3F, false).setUnlocalizedName("itemapple_swiftness").setTextureName("foodmod:itemapple_swiftness").setCreativeTab(FoodMod.FoodMod);
		itemapple_strength = new Itemapple_strength(4, 0.3F, false).setUnlocalizedName("itemapple_strength").setTextureName("foodmod:itemapple_strength").setCreativeTab(FoodMod.FoodMod);
		itemcandyboat = new Itemcandyboat().setUnlocalizedName("itemcandyboat").setTextureName("foodmod:itemcandyboat").setCreativeTab(FoodMod.TestStuff);
		itemapple_posion = new Itemapple_posion(4, 0.3F, false).setUnlocalizedName("itemapple_posion").setTextureName("foodmod:itemapple_posion").setCreativeTab(FoodMod.FoodMod);
		itemapple_fireresistance = new Itemapple_fireresistance(4, 0.3F, false).setUnlocalizedName("itemapple_fireresistance").setTextureName("foodmod:itemapple_fireresistance").setCreativeTab(FoodMod.FoodMod);
		itemapple_posion = new Itemapple_posion(4, 0.3F, false).setUnlocalizedName("itemapple_posion").setTextureName("foodmod:itemapple_posion").setCreativeTab(FoodMod.FoodMod);
		itemapple_regeneration = new Itemapple_regeneration(4, 0.3F, false).setUnlocalizedName("itemapple_regeneration").setTextureName("foodmod:itemapple_regeneration").setCreativeTab(FoodMod.FoodMod);
		itemapple_waterbreathing = new Itemapple_waterbreathing(4, 0.3F, false).setUnlocalizedName("itemapple_waterbreathing").setTextureName("foodmod:itemapple_waterbreathing").setCreativeTab(FoodMod.FoodMod);
		itemapple_jump = new Itemapple_jump(4, 0.3F, false).setUnlocalizedName("itemapple_jump").setTextureName("foodmod:itemapple_jump").setCreativeTab(FoodMod.FoodMod);
		itemcandycane = new ItemFood(2, 0.3F, false).setUnlocalizedName("itemcandycane").setTextureName("foodmod:itemcandycane").setCreativeTab(FoodMod.FoodMod);
		itemcandycanestick = new ItemCandyCaneStick().setUnlocalizedName("itemcandycanestick").setTextureName("foodmod:itemcandycanestick").setCreativeTab(FoodMod.FoodMod);
		itemcandycanereed = new Itemcandycanereed().setUnlocalizedName("itemcandycanereed").setTextureName("foodmod:itemcandycanereed").setCreativeTab(FoodMod.FoodMod);
		itemnyanapple = new  ItemNyanApple(2, 0.3F, false).setUnlocalizedName("itemnyanapple").setTextureName("foodmod:itemnyanapple").setCreativeTab(FoodMod.FoodMod);
		itemvanillapuding = new  ItemFood(8, 0.8f, false).setUnlocalizedName("itemvanillapuding").setTextureName("foodmod:itemvanillapuding").setCreativeTab(FoodMod.FoodMod);
		itemchocolatepuding = new  ItemFood(8, 0.8f, false).setUnlocalizedName("itemchocolatepuding").setTextureName("foodmod:itemchocolatepuding").setCreativeTab(FoodMod.FoodMod);
		itemstrawberrypudding = new  ItemFood(8, 0.8f, false).setUnlocalizedName("itemstrawberrypudding").setTextureName("foodmod:itemstrawberrypudding").setCreativeTab(FoodMod.FoodMod);
		itembananapudding = new  ItemFood(8, 0.8f, false).setUnlocalizedName("itembananapudding").setTextureName("foodmod:itembananapudding").setCreativeTab(FoodMod.FoodMod);
		itemlemonpudding = new  ItemFood(8, 0.8f, false).setUnlocalizedName("itemlemonpudding").setTextureName("foodmod:itemlemonpudding").setCreativeTab(FoodMod.FoodMod);
		itemcookiesncreampudding = new  ItemFood(8, 0.8f, false).setUnlocalizedName("itemcookiesncreampudding").setTextureName("foodmod:itemcookiesncreampudding").setCreativeTab(FoodMod.FoodMod);
		itempistachiopudding = new  ItemFood(8, 0.8f, false).setUnlocalizedName("itempistachiopudding").setTextureName("foodmod:itempistachiopudding").setCreativeTab(FoodMod.FoodMod);
		itemcandyarrow = new Item().setUnlocalizedName("itemcandyarrow").setTextureName("foodmod:itemcandyarrow").setCreativeTab(FoodMod.FoodMod);
		itemcandybow = new ItemCandyBow().setTextureName("foodmod:itemcandybow").setCreativeTab(FoodMod.FoodMod);
		itemcandybed = new Itemcandybed().setUnlocalizedName("itemcandybed").setTextureName("foodmod:itemcandybed").setCreativeTab(FoodMod.TestStuff);
		//itemdrink = new ItemDrink().setUnlocalizedName("itemdrink").setTextureName("foodmod:itemdrink").setCreativeTab(FoodMod.FoodMod);
		itemfriedegg = new  ItemFood(1, 1f, false).setUnlocalizedName("itemfriedegg").setTextureName("foodmod:itemfriedegg").setCreativeTab(FoodMod.FoodMod);
		
		
		itemknife = new Itemknife(ToolMaterial.IRON).setUnlocalizedName("itemknife").setTextureName("foodmod:itemknife").setCreativeTab(FoodMod.FoodMod);
		
		
		//entityliving.addPotionEffect(new PotionEffect(ModName.potionName.id, 200, 1, false));
		
		//Structure Spawners
		itemcandycanestructure = new Itemcandycanestructure().setUnlocalizedName("itemcandycanestructure").setTextureName("foodmod:itemcandycanestructure").setCreativeTab(FoodMod.TestStuff);
		
		registerItems();
	
	}
	
	



	/**
	 * Register Items.
	 */
	private static void registerItems(){
		
	    GameRegistry.registerItem(itemdiamondapple, itemdiamondapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcoalapple, itemcoalapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgoldapple, itemgoldapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemredstoneapple, itemredstoneapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itememeraldapple, itememeraldapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlapizapple, itemlapizapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemironapple, itemironapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemnetherstarapple, itemnetherstarapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemdragoneggapple, itemdragoneggapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcheese, itemcheese.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgrilledcheese, itemgrilledcheese.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemflesh, itemflesh.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcookedflesh, itemcookedflesh.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembacon, itembacon.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcheesecake, itemcheesecake.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcarrotcake, itemcarrotcake.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemBarkbread, itemBarkbread.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemKubdari, itemKubdari.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemRicebread, itemRicebread.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemtoast, itemtoast.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemČesnica, itemČesnica.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemSlicedbread, itemSlicedbread.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchocolatebar, itemchocolatebar.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchocolatemilk, itemchocolatemilk.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempizza, itempizza.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemicecream, itemicecream.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcorndog, itemcorndog.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcorndog_ketchup, itemcorndog_ketchup.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcorndog_mustard, itemcorndog_mustard.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemhotdog, itemhotdog.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcottoncandy_pink, itemcottoncandy_pink.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcottoncandy_blue, itemcottoncandy_blue.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemapplepie, itemapplepie.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcandyapple, itemcandyapple.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemsugarcookie, itemsugarcookie.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemoreo, itemoreo.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(item_mms, item_mms.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlemonade, itemlemonade.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlemon, itemlemon.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmeatball, itemmeatball.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmeatballraw, itemmeatballraw.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempasta, itempasta.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempeanut, itempeanut.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembean, itembean.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgoatmilk, itemgoatmilk.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemfishsticks, itemfishsticks.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemfishsticksraw, itemfishsticksraw.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempie, itempie.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmutton, itemmutton.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmuttonraw, itemmuttonraw.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlamb, itemlamb.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlambraw, itemlambraw.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemCheesecakeStuffedStrawberries, itemCheesecakeStuffedStrawberries.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemstrawberry, itemstrawberry.getUnlocalizedName().substring(5));   
	    GameRegistry.registerItem(itemblueberry, itemblueberry.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemblackberry, itemblackberry.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcherry, itemcherry.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemsoup, itemsoup.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemfrenchfry, itemfrenchfry.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlemonpie, itemlemonpie.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemasparagus, itemasparagus.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembasil, itembasil.getUnlocalizedName().substring(5));    
	    GameRegistry.registerItem(itemcilantro, itemcilantro.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembroccoli, itembroccoli.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemorange, itemorange.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemkiwi, itemkiwi.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemredpepper, itemredpepper.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemtomato, itemtomato.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemavocado, itemavocado.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgreenpepper, itemgreenpepper.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemraspberries, itemraspberries.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempear, itempear.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempeach, itempeach.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemonions, itemonions.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgarlic, itemgarlic.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemginger, itemginger.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemadzukibeans, itemadzukibeans.getUnlocalizedName().substring(5));    
	    GameRegistry.registerItem(itemblackbeans, itemblackbeans.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemblackeyepeas, itemblackeyepeas.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgarbanzobeans, itemgarbanzobeans.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemkidneybeans, itemkidneybeans.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlentils, itemlentils.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempintobeans, itempintobeans.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemwhitebeans, itemwhitebeans.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembeetroot, itembeetroot.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmustard, itemmustard.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemketchup, itemketchup.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmayo, itemmayo.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemhoneymustard, itemhoneymustard.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemranch, itemranch.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembanana, itembanana.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgrits, itemgrits.getUnlocalizedName().substring(5));    
	    GameRegistry.registerItem(itempopcorn, itempopcorn.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcorn, itemcorn.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlettuce, itemlettuce.getUnlocalizedName().substring(5));    
	    GameRegistry.registerItem(itemgreen_tomato, itemgreen_tomato.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlime, itemlime.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgrape, itemgrape.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcream, itemcream.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembutter, itembutter.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemice, itemice.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempufferfish_cooked, itempufferfish_cooked.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemclownfish_cooked, itemclownfish_cooked.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchickensoup, itemchickensoup.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchickenwings, itemchickenwings.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchickenwingsraw, itemchickenwingsraw.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchickenleg, itemchickenleg.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchickenlegraw, itemchickenlegraw.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchicken_nuggets, itemchicken_nuggets.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchicken_nuggetsraw, itemchicken_nuggetsraw.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcabbage, itemcabbage.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembun, itembun.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itempickle, itempickle.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcucumber, itemcucumber.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemsquash, itemsquash.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemlemonjuice, itemlemonjuice.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmashedbananas, itemmashedbananas.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchoppednuts, itemchoppednuts.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemchoppedgrass, itemchoppedgrass.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembakingpowder, itembakingpowder.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemcinnamon, itemcinnamon.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgroundginger, itemgroundginger.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemalmonds, itemalmonds.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemgroundalmonds, itemgroundalmonds.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemhoney, itemhoney.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemsesameseeds, itemsesameseeds.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemshortening, itemshortening.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembrownsugar, itembrownsugar.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmeltedbutter, itemmeltedbutter.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembayleaf, itembayleaf.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemhamburger, itemhamburger.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembeefbroth, itembeefbroth.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemjalapenopeppers, itemjalapenopeppers.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemmintleaves, itemmintleaves.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itembuttercandy, itembuttercandy.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemhorsemeat, itemhorsemeat.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemhorsemeat_raw, itemhorsemeat_raw.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemluckycandy, itemluckycandy.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemunstablecandy, itemunstablecandy.getUnlocalizedName().substring(5));
	    GameRegistry.registerItem(itemsugarcube, itemsugarcube.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemflour, itemflour.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemapple_swiftness, itemapple_swiftness.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemapple_strength, itemapple_strength.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcandyboat, itemcandyboat.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemapple_posion, itemapple_posion.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemapple_fireresistance, itemapple_fireresistance.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemapple_regeneration, itemapple_regeneration.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemapple_waterbreathing, itemapple_waterbreathing.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemapple_jump, itemapple_jump.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcandycane, itemcandycane.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcandycanestick, itemcandycanestick.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcandycanereed, itemcandycanereed.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemnyanapple, itemnyanapple.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemvanillapuding, itemvanillapuding.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemchocolatepuding, itemchocolatepuding.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemstrawberrypudding, itemstrawberrypudding.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itembananapudding, itembananapudding.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemlemonpudding, itemlemonpudding.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcookiesncreampudding, itemcookiesncreampudding.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itempistachiopudding, itempistachiopudding.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcandyarrow, itemcandyarrow.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcandybow, itemcandybow.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcandycanestructure, itemcandycanestructure.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemcandybed, itemcandybed.getUnlocalizedName().substring(5));
		//GameRegistry.registerItem(itemdrink, itemdrink.getUnlocalizedName().substring(5));
		GameRegistry.registerItem(itemfriedegg, itemfriedegg.getUnlocalizedName().substring(5));
		
		
		GameRegistry.registerItem(itemknife, itemknife.getUnlocalizedName().substring(5));
		
	}
}


